# Generated by Django 4.0.4 on 2022-05-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
