# Generated by Django 4.0.4 on 2022-05-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_cart_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='apartment',
            field=models.IntegerField(null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='cart',
            name='building',
            field=models.IntegerField(null=True, verbose_name='Строение'),
        ),
        migrations.AddField(
            model_name='cart',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='cart',
            name='corpus',
            field=models.IntegerField(null=True, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='cart',
            name='entrance',
            field=models.IntegerField(null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='cart',
            name='floor',
            field=models.IntegerField(null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='cart',
            name='house',
            field=models.IntegerField(null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='cart',
            name='street',
            field=models.CharField(max_length=30, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Имя'),
        ),
    ]
