# Generated by Django 4.0.4 on 2022-05-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_apartment_cart_building_cart_city_cart_corpus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_cart', to='store.product', verbose_name='Добавление в корзину'),
        ),
    ]
