# Generated by Django 4.0.4 on 2022-05-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='apartment',
            field=models.IntegerField(default=1, verbose_name='Квартира'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='building',
            field=models.IntegerField(default=1, verbose_name='Строение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='city',
            field=models.CharField(default=1, max_length=30, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='corpus',
            field=models.IntegerField(default=1, verbose_name='Корпус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='entrance',
            field=models.IntegerField(default=1, verbose_name='Подъезд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Подъезд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='street',
            field=models.CharField(default=1, max_length=30, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
