# Generated by Django 4.0.4 on 2022-05-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cart_apartment_alter_cart_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='buy_product', to='store.cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='house',
            field=models.IntegerField(default=1, verbose_name='Дом'),
            preserve_default=False,
        ),
    ]
