# Generated by Django 4.0.4 on 2022-05-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
