# Generated by Django 4.0.4 on 2022-05-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(db_index=True, default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
