# Generated by Django 4.0.4 on 2022-05-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_add']},
        ),
    ]
